### ISSUE TITLE
show correct answer sets the session with the correct answer

### ISSUE THREAD

**Issue by edeustace** [PieLabs/corespring-pie-d3-pie-chart-polymer-ralf#1]
when you use `show correct answer` the correct answer is being set on the session object. This shouldn't be the case, as it could cause the session to be set incorrectly - the correct answer should be internal to the pie and only used for rendering. we should have this set up in corespring-pie-multiple-choice.

<img width="1158" alt="screen shot 2016-09-12 at 11 58 33" src="https://cloud.githubusercontent.com/assets/101623/18433581/5032236e-78e0-11e6-9577-708859df9a05.png">

**Comment by ghost** [comment]
thanks for the report, should be fixed now
